### ISSUE TITLE
when converting from the h2 test db to a a maria db

### ISSUE THREAD

**Issue by iAmGiG** [GIGA-Money/spring-react#3]
An issue exist where we attempt to follow the book when using maria db as our solution for database manipulation. we get the following error:
```Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.springreact.springreact.SpringreactApplication.<clinit>(SpringreactApplication.java:29)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more
```
it is not exactly clear why.
the new application.properties file looks like:
```spring.datasource.url=jdbc:mariadb://localhost:3360
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

logging.level.root=INFO```

beginning research

**Comment by iAmGiG** [comment]
confirmed the maria db connection with dbeaver and HeidiSql to be working.  issues may exist with spring initialization.
